In [9]:
import numpy as np
a = [1,2,3,4]
b = [5,6,7,8]
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [12]:
[a[i] + b[i] for i in range(len(a))]

[6, 8, 10, 12]

In [14]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [17]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr[1:,1:] #start_row:end_row,start_col:end_col

array([[5, 6],
       [8, 9]])

In [28]:
arr[:,1:2]

array([[2],
       [5],
       [8]])

In [52]:
arr[-2:,:-2]

array([[4],
       [7]])

In [54]:
np.eye(3,3).astype(int).dtype

dtype('int64')

In [55]:
np.eye(3,3).astype("int32").dtype

dtype('int32')

In [57]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [59]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [60]:
a = np.arange(10)

In [61]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [63]:
np.linspace(0,11,5)

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [ ]:
## Vector Operation 

In [64]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [65]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [68]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [67]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [71]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [72]:
np.linalg.det(a)

np.float64(-9.51619735392994e-16)

In [96]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3,4,5,6]])

In [75]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
b

array([[1, 2, 3, 4, 5, 6]])

In [81]:
a = np.array([1,2,3,4,5,6,7,8,9,10,4,1])

In [82]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1])

In [89]:
np.resize(a,(4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  4,  1],
       [ 1,  2,  3,  4]])

In [90]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10,  4,  1])]

In [91]:
np.split(a,4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10,  4,  1])]

In [104]:
arr = np.array([1,2,3,4,5,6])

In [105]:
b = arr.view()

In [106]:
b[0] = 10

In [108]:
arr,b

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [109]:
c = arr.copy()

In [110]:
arr,c

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [111]:
c[0] = 11

In [112]:
arr,c

(array([10,  2,  3,  4,  5,  6]), array([11,  2,  3,  4,  5,  6]))

In [114]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
np.sum(a,axis=0)

array([12, 15, 18])

In [116]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [18]:
import numpy as np
def mean(array):
    n = len(array)
    return np.sum(array)/n

In [19]:
mean(np.array([1,2,3,4,5,6]))

np.float64(3.5)

In [20]:
def variance(array):
    n = len(array)
    m = mean(array)
    return np.sum((array-m)**2)/n

In [21]:
variance(np.array([1,2,3,4,5,6]))

np.float64(2.9166666666666665)

In [39]:
arr = np.array([1,2,3,4])
scalar = 5

In [40]:
result = arr + scalar

In [41]:
result

array([6, 7, 8, 9])

In [42]:
res = arr * scalar

In [43]:
res

array([ 5, 10, 15, 20])

In [50]:
data = np.array([10,3,7,4,9])

In [51]:
min_val = np.min(data)

In [52]:
max_val = np.max(data)

In [53]:
res1 = (data - min_val)/(max_val - min_val)

In [54]:
res1

array([1.        , 0.        , 0.57142857, 0.14285714, 0.85714286])

In [55]:
min_val

np.int64(3)

In [56]:
max_val

np.int64(10)